function ModPar = getModPar_Riser (xS) 

% 04/05/2021 @ Franklin Court, Cambridge  [J Yang]

% assign the values using the options below 
Ca      = xS(1);
Cd      = xS(2);
rho     = xS(3);
E       = xS(4);
rho_oil = xS(5);
T0      = xS(6);

ModPar = struct ( ...
         'Struct_type',  2 ,                ...   % choose struture type Riser == 2
     ... ---------------------------------------------------------------
     ... % options to control    
     ... --------------------------------------------------------------- 
         'wavetype'   ,  2 ,                ...   % choose wave type, regular == 1, random == 2
         'calcType' ,    1 ,                ...   % choose freuqency == 1 or time == 2
     ... % calculation parameters
         'om_range'  ,  (0.1:0.05:2),      ...   % choose frequency range 
         'tmax'      ,  2*pi/0.05*4,        ...     
         'dtScale'    ,  20,                ...   % scale time step, bigger --> finer 
     ... % parameters of random sea states 
         ... % combination of Hs = 1.5 and Tz = 7.5 have high occurance according to scatter diagram for North Atlantic (DNVGL-C205)
         'wavecode' ,    1 ,                 ...  % choose Jonswap wave (at the moment only this representative sea state)
        'jonswapHs'   , 1.5 ,                ...  % wave height
        'jonswapTz'   , 7.5,                  ...  % zero up-crossing period Tz, and peak wave period Tp = 1.2859*Tz (for the Jonswap parameter used )    
    ... ---------------------------------------------------------------
     ... % to test the code, the following parameters should be left as it is 
     ... ---------------------------------------------------------------    
     ... % options 
         'bendingCalc', 'EI' ,...   
         'bodyflex' ,    1 , ...
         'aw'      ,    1 , ...
         'Nfft'    ,   2^11, ...
         'Nwin'     ,  2^5,  ...
         'Ndof'     ,   40,   ...
         'Nvb'     ,	6,   ...
         'wLim'     ,   5,   ...
         'g'        ,  9.81, ...
         'typeIntTLP', 'decay with plateau',...
         'isModelTest', 0, ...
     ... % Morison parameters
        'Ca'         ,  Ca, ...
        'Cd'         ,  Cd, ...
     ... % material parameters
        'rho'        ,  rho , ...
        'rho_f'      ,  1.025e3, ...
        'rho_oil'    ,  rho_oil,  ...
        'E'          ,  E,   ...
     ... % platform related 
        'T0'         ,  T0,  ...
        'T_TLP'      ,  5:1:18,      ...
        'H_TLP'      ,  [0.14 0.12 0.14 0.16 0.08 0.14 0.30 0.44 0.56 0.66 0.76 0.82 0.9 0.94 ],     ...
        'gamma_TLP' ,  [ones(1,length([5:8]))*(-pi/2) ones(1,length([9:18]))*(pi/2)] ,      ...
     ... % geometries of structure
         'Nsec'     ,   1,      ...
         'rhoC'     ,   1,       ...
        'Din'        ,  0.374,   ...
        'Dout'       ,  0.406,   ...
        'De'         ,  0.660,    ...
         'L'        ,   500,       ...
         'Li'       ,   1,       ...
         'L1'       ,   0,      ...
         'L2'       ,   500,     ...
     ... % model testing related 
         'L_b'     ,   [],      ...
         'mb'     ,    [],          ...
          'd'     ,    [],          ...         
     ... % 
         's_alpha' ,    0); 
     

        