
function ModPar = getModPar_FWTtank (xS) 
% This list below is prepared for simulation of hydrodynamic response of a
% floating spar (representing Hywind floating wind turbine -FWT) in a wave
% tank environment 
% I have adapted this list and choose to randomnize some of the parameters

% 21/04/2021 @ Franklin Court, Cambridge  [J Yang] 


% the list of random parameters. This needs to be consistent with the input
% file. future improvement will try to remove this duplication 
    rho     = xS(1);
    rho_f   = xS(2);
    Ca      = xS(3);
    Cd      = xS(4);
    L_b     = xS(5);
    r       = xS(6);
    t       = xS(7);
    mb      = xS(8);
    E       = xS(9);
    
   
% assign the values using the options below 

ModPar = struct ( ...
         'Struct_type',  1 ,                ...   % choose struture type FWT == 1
          'isModelTest', 1,                 ...   % choose model testing for wave tank model
     ... ---------------------------------------------------------------
     ... % options to control    
     ... --------------------------------------------------------------- 
         'wavetype'   ,  1 ,                ...   % choose wave type, regular == 1, random == 2
         'calcType' ,    1 ,                ...   % choose freuqency == 1 or time == 2
     ... % calculation parameters
         'om_range'  ,  (0.1:0.5:2)*2*pi,      ...   % choose frequency range (this only controls harmonic wave)
         'tmax'      ,   1/0.1*5,        ...     
         'dtScale'    ,  20,                ...   % scale time step, bigger --> finer 
     ... % parameters of random sea states 
         ... % combination of Hs = 1.5 and Tz = 7.5 have high occurance according to scatter diagram for North Atlantic (DNVGL-C205)
         'wavecode' ,    1 ,                 ...  % choose Jonswap wave (at the moment only this representative sea state)
        'jonswapHs'   , 1.5 ,                ...  % wave height
        'jonswapTz'   , 7.5,                  ...  % zero up-crossing period Tz, and peak wave period Tp = 1.2859*Tz (for the Jonswap parameter used )    
     ... ---------------------------------------------------------------
     ... % to test the code, the following parameters should be left as it is 
     ... ---------------------------------------------------------------    
     ... % options 
         'bendingCalc', 'IR' ,...   
         'bodyflex' ,    0 , ...
         'aw'      ,    1 , ...
         'Nfft'    ,   2^11, ...
         'Nwin'     ,  2^5,  ...
         'Ndof'     ,   2,   ...
         'Nvb'     ,	2,   ...
         'wLim'     ,   5,   ...
         'g'        ,  9.81, ...
         'typeIntTLP', 'decay with plateau',...
     ... % Morison parameters
        'Ca'         ,  Ca, ...
        'Cd'         ,  Cd, ...
     ... % material parameters
        'rho'        ,  rho , ...
        'rho_f'      ,  rho_f, ...
        'rho_oil'    ,  0,  ...
        'E'          ,  E ,   ...
     ... % platform related 
        'T0'         ,  0,  ...
        'T_TLP'      ,  6:1:18,      ...
        'H_TLP'      ,  zeros(size([6:1:18])),     ...
        'gamma_TLP' ,  zeros(size([6:1:18])),      ...
     ... % geometries of structure
         'Nsec'     ,   2,      ...
         'rhoC'     ,   [1 0],       ...
        'Din'        ,  [2*(r-t) 0] ,   ...
        'Dout'       ,  [2*r 0],   ...
        'De'         ,  [2*r 0],    ...
         'L'       ,   [1 0.2],       ...
         'Li'       ,   [0.01 0.01],       ...
         'L1'       ,   0.2,      ...
         'L2'       ,   1,     ...
     ... % model testing related 
         'L_b'     ,   L_b,      ...
         'mb'     ,   mb,          ...
          'd'     ,   1,          ...
     ... % 
         's_alpha' ,    0 ); 
     
        
        